### PR TITLE
Added Timeout roulette with multiplayer

### PR DESCRIPTION
**Pull request by TheShining1**
[PR 162](https://github.com/Streamer-bot-Extensions/Streamer.bot-Extensions-Wiki/pull/162) TheShining1 [](https://translate.botextensions.dev/project/streamer-bot-extensions-wiki)   [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=Streamer-bot-Extensions&utm_campaign=badge_info)

[x] Included all images in documentation.
[x] Used relative pathing i.e. (/extensions/your extension/images/image.png).
[x] Included import file.
[x] Made sure that all variables were camelCase (Non-camelCase variables won't work so won't be approved).
[x] Detailed explanation of how your extension works (We test all of these so if we can't figure out how to use it the extension won't be approved).

Make sure to put an x in each check list item and that the items checked off have been completed.
Any extensions submitted with the checklist done and found not to be adhered to will be closed without warning.

### CODE REVIEW

**Comment by TheShining1** [comment]
I actually didn't understand "Included import file". It means just MD file? And about "Non-camelCase variables won't work" inside C# code or where?
If I made a mistake somewhere, let me know please )

**Review by TerrierDarts — CHANGES_REQUESTED** [review]
Does not follow the template. see other pages for details..
https://extensions.streamer.bot/en/documentation-writeup

**Comment by TheShining1** [comment]
Oh, sorry, I wasn't aware of new template page. I was using old one provided to me. Fixed.

**Comment by TerrierDarts** [comment]
Accepted, Thanks
Just for future reference please place references under the Installation header and Only use 1 link for the contribution

**Review by TerrierDarts — APPROVED** [review]

**Comment by TheShining1** [comment]
Noted,
Another question, I was told to fork this repo (https://github.com/GodOfWonders/Streamer.bot-Extensions-Wiki), but isn't it more logical to fork main repo instead?

**Comment by TerrierDarts** [comment]
Erm, that is prob a better question for Gowman or Web_Mage :) 

as i am not sure

**Comment by Web-Mage** [comment]
That may have been a typo from when GoWMan was writing up instructions. At the time I think he was using his personal repo because of sync errors we were getting between GitHub and the wiki.

Doing your fork/pull request here should be fine.

**Comment by TheShining1** [comment]
So I can fork main repo? It just looks nicer )

**Pull request merged**
