### PR TITLE
Create youtube-channel-rewards.md

### PR DESCRIPTION
**Pull request by tommerty**
[PR 203](https://github.com/Streamer-bot-Extensions/Streamer.bot-Extensions-Wiki/pull/203) tommerty [](https://translate.botextensions.dev/project/streamer-bot-extensions-wiki)  

Adding https://ytcr.gezel.io to the pool! I don't have a video up yet so I haven't included this. Once I work on the video however I will create another PR and push this

- [x] Included all images in documentation. (if using images please try use proper names)
- [x] Used relative pathing. i.e (/assets/hydrate/channelpointredeem.png)
- [ ] Included import file. (not Code but File)
- [x] All Images/Files or anything else related go in there own folder inside "Assets"
- [x] Heading Names are the same as on the documentation writeup page
- [x] Made sure that all variables were camelCase (Non-camelCase variables won't work so won't be approved).
- [x] Detailed explanation of how your extension works (We test all of these so if we can't figure out how to use it the extension won't be approved).

Make sure to put an x in each check list item and that the items checked off have been completed.
Any extensions submitted with the checklist done and found not to be adhered to will be closed without warning.

>Included import file. (not Code but File)

I have not done this as it can update regularly, so I'd rather have it linked to our repo if possible. If not, please @ me and let me know and I'll upload it separately

### CODE REVIEW

**Comment by tommerty** [comment]
Any chance of getting this reviewed? 😊

**Review by TerrierDarts — APPROVED** [review]

**Comment by tommerty** [comment]
Hey @TerrierDarts, is it possible to add this to the `EXTENSIONS` nav? Right now you can only find this by searching.

We don't have a fontawesome icon but `fa-rocket` would be good enough 😊

**Comment by TerrierDarts** [comment]
Things generally aren't added to the nav. You will need to put it on the pages of the category it falls under so in this case YouTube

**Comment by tommerty** [comment]
That's fair! How would I go about doing that exactly? Wouldn't be the most familiar with WikiJS. Thanks!

**Comment by TerrierDarts** [comment]
Each catagory has a page so in your case it would be `youtube.md` and you just follow how that one is done

**Pull request merged**
